### ISSUE TITLE
About pretrained models

### ISSUE THREAD

**Issue by FrankkkWang** [Yiming-M/CLIP-EBC#1]
It seems that you didn't  upload well your pertained models.Could you please provide another way to download them, such as Google Drive

**Comment by Yiming-M** [comment]
Hi @FrankkkWang ,

Thanks for letting me know. I have uploaded the weights on my Google Drive and you may access it from https://drive.google.com/drive/folders/1hEHRsyOxvtbnq8UR0iXnQ7kcKO7aaYVM?usp=sharing

Feel free to let me know if this doesn't work.

Many thanks,
Yiming
