### ISSUE TITLE
About the hyperparameter anchor_points

### ISSUE THREAD

**Issue by Chenguoz** [Yiming-M/CLIP-EBC#10]
Nice work! Regarding the selection of the hyperparameter `anchor_points`, I noticed that your code provides quite a few predefined settings for different datasets. Could you tell me how these settings were determined in your code? Additionally, if I need to train on a custom dataset, how should I choose the optimal `anchor_points`?

**Comment by Yiming-M** [comment]
Hi @Chenguoz ,

For each bin, the **anchor point** (in the paper we call it the **representative count value**) is obtained by averaging the count values falling into that bin. You may also try to use the middle point of each bin (e.g., 3 for the bin [2, 4)) as the anchor point to avoid complication.

Many thanks,
Yiming
