### ISSUE TITLE
Generating Caption

### ISSUE THREAD

**Issue by NusratTahira** [Yiming-M/CLIP-EBC#13]
Hello,
Thank you for sharing the impressive work you've done on crowd counting. I'm particularly interested in learning more about how you generated the captions that are shown in the paper.

Would you be able to provide some details on the process you used to create those captions during the testing phase of your experiments?

**Comment by Yiming-M** [comment]
Hi @NusratTahira 

Our model does not generate captions (actually I don't think we ever mentioned caption generation in our paper). Instead, it produces probability maps over pre-defined bins and density maps (expectation over the pre-defined bins).

Many thanks,
Yiming

**Comment by NusratTahira** [comment]
In the model architecture you have shown there are some texts and also when the model starts training or testing it shows "Initialized model with texts...". How do you get the text while testing?
![Picture1](https://github.com/Yiming-M/CLIP-EBC/assets/160222029/88bada3c-dc57-42a5-9e90-b0dc10992056)
![Screenshot from 2024-07-05 15-40-40](https://github.com/Yiming-M/CLIP-EBC/assets/160222029/21a797b0-0966-4a29-9397-82885b91dfb7)

**Comment by Yiming-M** [comment]
These texts used in testing are the same as the ones used in training. You can comment the `print` function at [models/clip/model.py L122](https://github.com/Yiming-M/CLIP-EBC/blob/c046c20ca83d4f2ccc774f1769f7cd9b60114c91/models/clip/model.py#L122) if you don't want this output.
