### ISSUE TITLE
Error in evaluation

### ISSUE THREAD

**Issue by BurstLink666** [Yiming-M/CLIP-EBC#14]
Hi, I got an error during the evaluation.  

Traceback (most recent call last):
  File "/mnt/share/herenjie/CLIP-EBC/trainer.py", line 245, in <module>
    main()
  File "/mnt/share/herenjie/CLIP-EBC/trainer.py", line 241, in main
    run(0, 1, args)
  File "/mnt/share/herenjie/CLIP-EBC/trainer.py", line 169, in run
    curr_val_scores = evaluate(
  File "/mnt/share/herenjie/CLIP-EBC/eval.py", line 35, in evaluate
    assert image_height % window_size == 0 and image_width % window_size == 0, f"Image size {image.shape} should be divisible by window size {window_size}."
AssertionError: Image size torch.Size([1, 3, 704, 1024]) should be divisible by window size 448.

It seems that some images in val datasets cannot be divided by 448, which is the default window_size as you provided after executing preprocess.sh. I got this error when training clip_resnet50 in ShanghaiTec_partA with input_size 448. How can I fix it?

**Comment by Yiming-M** [comment]
Hi @BurstLink666 ,

Thanks for report this issue!
I forgot to update `eval.py`, which caused the bug. Can you please check whether it has been fixed in https://github.com/Yiming-M/CLIP-EBC/commit/bda84f6541ac7c34894d4694fe47bd53ff564850?

Many thanks,
Yiming

**Comment by BurstLink666** [comment]
Everything goes well now, thank you very much. 

Here I have another question. In the .json file in configs folder, it seems that you provide different reduction strategies for different dataset. Can you explain the meaning of the attribute "bins" and "anchor_points", especially the values? And if I want to adapt your work to a new dataset, how to set these values?

**Comment by BurstLink666** [comment]
> Hi @BurstLink666 ,
> 
> Thanks for report this issue! I forgot to update `eval.py`, which caused this bug. I have fixed it and things should work fine now! Feel free to reopen this issue if that's not the case.
> 
> Many thanks, Yiming

Everything goes well now, thank you very much.

Here I have another question. In the .json file in configs folder, it seems that you provide different reduction strategies for different dataset. Can you explain the meaning of the attribute "bins" and "anchor_points", especially the values? And if I want to adapt your work to a new dataset, how to set these values?
