### ISSUE TITLE
Testing on a different dataset

### ISSUE THREAD

**Issue by DoaaAburayya** [Yiming-M/CLIP-EBC#18]
Hello,

Could you please tell me how I can test the model's weights on a different dataset than the one you used?

Thank you

**Comment by Yiming-M** [comment]
Hi @DoaaAburayya ,

Sorry for this late reply.

Given an image of shape `(1, C, H, W)`, our CLIP-EBC implementation directly produces a density map of shape `(1, 1, H // r, W // r)` in the `eval` mode, where `r` is the model-related reduction factor. If you need to get the total predicted count, you may simply sum up the values of the density map. If you need the density map for visualization purposes, you may have to resize it to the spatial size of the input image.

Many thanks,
Yiming
