### ISSUE TITLE
Finetune

### ISSUE THREAD

**Issue by hatmore** [Yiming-M/CLIP-EBC#8]
Have you tried freezing the image encoder, using an adaptor or a  branch to finetune CLIP, instead of directly finetuning the image encoder? Could there be some losses with direct fine-tuning of the image encoder?

**Comment by DKk771** [comment]
Hello, please ask AssertionError: NwPu test split should have 1500 images, but found 0. Do not recognize the data set, how to solve it? Thank you

**Comment by Yiming-M** [comment]
> Have you tried freezing the image encoder, using an adaptor or a branch to finetune CLIP, instead of directly finetuning the image encoder? Could there be some losses with direct fine-tuning of the image encoder?

Hi @hatmore ,

Thanks for your interest in our work and also your kind suggestion. However, in this project we intend to figure out whether the CLIP possess the ability to count. There have been several other works that also use CLIP (e.g., [CLIP-Count](https://github.com/songrise/CLIP-Count), [VL-Counter](https://github.com/Seunggu0305/VLCounter)), but they all somehow modify the structure of CLIP. In contrast, our work CLIP-EBC is the first CLIP-based model that preserves the original structure of CLIP to the maximum extent, which means we did not freeze the encoder and use adaptors to enable the model to count.

Many thanks,
Yiming

**Comment by Yiming-M** [comment]
> Hello, please ask AssertionError: NwPu test split should have 1500 images, but found 0. Do not recognize the data set, how to solve it? Thank you

Hi, please run the preprocessing code :)

**Comment by DKk771** [comment]
Thank you so much




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Yiming-M/CLIP-EBC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月8日(星期三) 晚上7:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Yiming-M/CLIP-EBC] Finetune (Issue #8)





  
Hello, please ask AssertionError: NwPu test split should have 1500 images, but found 0. Do not recognize the data set, how to solve it? Thank you
  
Hi, please run the preprocessing code :)
