### ISSUE TITLE
using the model on an edge device

### ISSUE THREAD

**Issue by seunghalee1226** [Yiming-M/CLIP-EBC#9]
Hello, thank you for sharing the great resources. 
I am currently looking to use this model on an edge device. Have you tested it on an edge device by any chance? 
The edge device I plan to use is the **Jetson Orin Nano NX 16GB.**

**Comment by Yiming-M** [comment]
Hi @seunghalee1226 ,

Sorry I don't have any experience in implementing models in edge devices.

Many thanks,
Yiming
